RUN git clone -b dev --single-branch --depth 1 https://github.com/Koenkk/zigbee2mqtt.git /opt/zigbee2mqtt \
    && rm -rf \ 
    /opt/zigbee2mqtt/data \ 
    /opt/zigbee2mqtt/docs \ 
    /opt/zigbee2mqtt/test \ 
    /opt/zigbee2mqtt/images \ 
    /opt/zigbee2mqtt/scripts \ 
    /opt/zigbee2mqtt/docker \ 
    /opt/zigbee2mqtt/LICENSE \ 
    /opt/zigbee2mqtt/README.md \ 
    /opt/zigbee2mqtt/update.sh \
    /opt/zigbee2mqtt/npm-shrinkwrap.json \
    && ln -s /data /opt/zigbee2mqtt/data \